# Generated by Django 4.1 on 2023-02-03 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cartoonization", "0002_remove_getvideo_id_alter_getvideo_v_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="getvideo",
            name="v_id",
        ),
        migrations.AddField(
            model_name="getvideo",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
